[package]
name = "P1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "p1"
path = "src/main.rs"

[dependencies]
num-traits = "0.2.15"
glfw = "0.51.0"

